#! /bin/bash

SWWW_TRANSITION=random
export stills="$1"

wallpaper () {
    for monitor in "${monitors[@]}"; do swww img --outputs $monitor "$(randstill)"; done
  }

#Function to select a random file from $stills directory
randstill() {
    find "$stills" -maxdepth 1 -type f | shuf -n 1
}

#Switches wallpaper based on charging status
wptoggle () {
    #Identify active monitors
    monitors=($(hyprctl monitors | awk '{if ($1 ~ "Monitor") print $2}'))
    hyprctl keyword de;coration:blur_new_optimizations 1

    wallpaper
    while pgrep swww; do
      sleep 300
      wallpaper
    done
  }

#perform cleanup and exit
trap 'pkill swww & exit' exit 1 3 15

swww init
wptoggle
