#!/bin/sh

# load $WALLPAPER_IMAGE environment variable
source $HOME/.config/hypr/scripts/variables/load_envs

function load_wp(){
    swww img -t any --transition-speed 200 --transition-step 255 --transition-fps 60 $BACKGROUND_IMAGE
}

#perform cleanup and exit
# trap 'pkill swww' exit 1 3 15
# trap 'swww kill & exit' exit 1 3 15

if ! swww query; then
    swww init
fi

load_wp