#!/bin/bash
EWW_BIN="/usr/bin/eww -c $HOME/.config/hypr/themes/apatheia/eww"

# select widget for pirmary monitor
primary=($($HOME/.config/hypr/configs/primary));
WIDGET=$1
WIDGET+=$primary

# Open widgets
if ${EWW_BIN} windows | grep ^$WIDGET$ ; then
    ${EWW_BIN} close "system${primary}" "audio_ctl${primary}" "calendar${primary}"
    ${EWW_BIN} open "$WIDGET"
elif ${EWW_BIN} windows | grep ^\*$WIDGET$ ; then
    ${EWW_BIN} close "$WIDGET"
else exit
fi
