#!/bin/bash
EWW_BIN="/usr/bin/eww -c $HOME/.config/hypr/themes/apatheia/eww"

# select widget for focused monitor
focusmon=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .id')
WIDGET=$1
WIDGET+=$focusmon

# Open widgets
if ${EWW_BIN} windows | grep ^$WIDGET$ ; then
    ${EWW_BIN} close "system${focusmon}" "audio_ctl${focusmon}" "calendar${focusmon}"
    ${EWW_BIN} open "$WIDGET"
elif ${EWW_BIN} windows | grep ^\*$WIDGET$ ; then
    ${EWW_BIN} close "$WIDGET"
else exit
fi
