#!/bin/bash

function setPrimaryMonitor(){
    save_location=~/.config/hypr/scripts/variables/temp/primary_screen
    touch $save_location
    echo $1 > $save_location
}

function setBackgroundImage(){
    save_location=~/.config/hypr/scripts/variables/temp/background
    touch $save_location
    echo $1 > $save_location
}


doc() {
    echo "Usage:
    set_env [Options]

    Options:
        primary     Sets the primary screen
        background  Sets the image location of the active wallpaper"
}

case $1 in
    primary)		setPrimaryMonitor $2		;;
    background)		setBackgroundImage $2       ;;
    help)           doc                         ;;
    *)              doc                         ;;            
esac
