#!/bin/bash
save_location=~/.config/hypr/scripts/variables/temp

function setVar(){
    checkENVDir $2
    echo $1 > "$save_location/$2"
}

function checkENVDir() {
    if ! test -d "$save_location"; then
        mkdir $save_location
    fi
    if ! test -f "$save_location/$1"; then
        touch $save_location/$1
    fi
}

doc() {
    echo "Usage:
    set_env [Options]

    Options:
        primary     Sets the primary screen
        background  Sets the image location of the active wallpaper"
}

case $1 in          #function #file param #file name
    primary)		setVar $2 primary_screen	;;
    background)		setVar $2 background        ;;
    help)           doc                         ;;
    *)              doc                         ;;            
esac
