#!/bin/bash
TERM=kitty          #Tag 1
BROWSER=brave       #Tag 2
DOC=libreoffice     #Tag 3
FILE=dolphin        #Tag 4
PLAYER=vlc          #Tag 5
GAME=steam-native   #Tag 6
PHOTO=krita         #Tag 7
SANDBOX="mailspring --no-sandbox"  #Tag 8
DEV=neovide         #Tag 9

#Lookup Focused tag
TAG=$(hyprctl monitors | grep -B 4 "focused: yes" | awk 'NR==2 {print $1}' RS='(' FS=')')

#Executes application based on number of focused tag
case "$TAG" in 
  1) $TERM &> /dev/null ;;
  2) $BROWSER &> /dev/null ;;
  3) $DOC &> /dev/null ;;
  4) $FILE &> /dev/null ;;
  5) $PLAYER &> /dev/null ;;
  6) $GAME &> /dev/null ;;
  7) $PHOTO &> /dev/null ;;
  8) $SANDBOX &> /dev/null ;;
  9) $DEV &> /dev/null ;;
esac
