#! /bin/bash

#define icons for workspaces 1-9
ic=(0     輸    )

workspaces() {

unset -v \
  o1 o2 o3 o4 o5 o6 o7 o8 o9 \
  f1 f2 f3 f4 f5 f6 f7 f8 f9

# check if Occupied
for num in $(hyprctl workspaces | grep ID | awk '{print $3}'); do 
  export o"$num"="$num"
done
                                       
 
#check if Focused
for num in $(hyprctl monitors | grep -B 4 "active: yes" | awk 'NR==1{print $3}'); do 
  export f"$num"="$num"
done

echo 	"(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
          (box	:class \"works\"	:orientation \"h\" :spacing 5 :space-evenly \"true\" 	\
              (button :onclick \"~/.config/hypr/apatheia/scripts/workspace 1\" :onrightclick \"~/.config/hypr/apatheia/scripts/workspace 1 && ~/.config/hypr/apatheia/scripts/default_app\"   :class \"0$o1$f1\" \"${ic[1]}\") \
              (button :onclick \"~/.config/hypr/apatheia/scripts/workspace 2\" :onrightclick \"~/.config/hypr/apatheia/scripts/workspace 2 && ~/.config/hypr/apatheia/scripts/default_app\"	  :class \"0$o2$f2\" \"${ic[2]}\") \
              (button :onclick \"~/.config/hypr/apatheia/scripts/workspace 3\" :onrightclick \"~/.config/hypr/apatheia/scripts/workspace 3 && ~/.config/hypr/apatheia/scripts/default_app\"	  :class \"0$o3$f3\" \"${ic[3]}\") \
              (button :onclick \"~/.config/hypr/apatheia/scripts/workspace 4\" :onrightclick \"~/.config/hypr/apatheia/scripts/workspace 4 && ~/.config/hypr/apatheia/scripts/default_app\"	  :class \"0$o4$f4\" \"${ic[4]}\") \
              (button :onclick \"~/.config/hypr/apatheia/scripts/workspace 5\" :onrightclick \"~/.config/hypr/apatheia/scripts/workspace 5 && ~/.config/hypr/apatheia/scripts/default_app\"	  :class \"0$o5$f5\" \"${ic[5]}\") \
              (button :onclick \"~/.config/hypr/apatheia/scripts/workspace 6\" :onrightclick \"~/.config/hypr/apatheia/scripts/workspace 6 && ~/.config/hypr/apatheia/scripts/default_app\"	  :class \"0$o6$f6\" \"${ic[6]}\") \
              (button :onclick \"~/.config/hypr/apatheia/scripts/workspace 7\" :onrightclick \"~/.config/hypr/apatheia/scripts/workspace 7 && ~/.config/hypr/apatheia/scripts/default_app\"	  :class \"0$o7$f7\" \"${ic[7]}\") \
              (button :onclick \"~/.config/hypr/apatheia/scripts/workspace 8\" :onrightclick \"~/.config/hypr/apatheia/scripts/workspace 8 && ~/.config/hypr/apatheia/scripts/default_app\"	  :class \"0$o8$f8\" \"${ic[8]}\") \
              (button :onclick \"~/.config/hypr/apatheia/scripts/workspace 9\" :onrightclick \"~/.config/hypr/apatheia/scripts/workspace 9 && ~/.config/hypr/apatheia/scripts/default_app\"	  :class \"0$o9$f9\" \"${ic[9]}\") \
          )\
        )"
}

workspaces
#tail -f /tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/hyprland.log | grep --line-buffered "Changed to workspace" | while read -r; do 
socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r; do 
workspaces
done
