#!/bin/bash

## Files and cmd
EWW="eww -c $HOME/.config/hypr/themes/apatheia/eww/"
focusmon=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .id')

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
	${EWW} daemon
	sleep 1
fi

# primary display id
primary=($($HOME/.config/hypr/configs/primary));

## Open widgets 
NB_MONITORS=($(hyprctl monitors -j | jq -r '.[] | .id'))
for id in "${NB_MONITORS[@]}"; do
    # make top bar for every display
    bar="bar$id"
    hyprctl dispatch focusmonitor "$id"
    ${EWW} open "$bar" 
    
    # make sidebar and notifications popup only for primary display
    [[ $id == $primary ]] && ${EWW} open-many "sidebar$id" notifications
done
    hyprctl dispatch focusmonitor "$focusmon"
    