#!/bin/bash

## Files and cmd
EWW="eww -c $HOME/.config/hypr/themes/apatheia/eww/"
focusmon=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .id')

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
	${EWW} daemon
	sleep 1
fi

## Open standard widgets 
NB_MONITORS=($(hyprctl monitors -j | jq -r '.[] | .id'))
for id in "${NB_MONITORS[@]}"; do
    # make top bar for every display
    bar="bar$id"
    hyprctl dispatch focusmonitor "$id"
    ${EWW} open "$bar" 

    # set calendar widget
    # cal="calendar$id"
    # ${EWW} open "$cal" 
done
    hyprctl dispatch focusmonitor "$focusmon"

# Open widgets for primary display
primary=($($HOME/.config/hypr/themes/apatheia/eww/scripts/get_primary))
${EWW} open-many "sidebar$primary" "notifications$primary"